import { Html, Head, Main, NextScript } from 'next/document'
import NavBar from '../components/Navbar';
import Footer from '../components/Footer';
export default function Document() {
    return (
        <Html>
            <Head>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <body>
                <NavBar />
                <Main />
                <NextScript />
                <Footer/>
            </body>
        </Html>
    );
};