import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
    return (
        <Html>
            <Head>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <body>
                <nav className="navbar navbar-light bg-light">
                    <h4>This is h4</h4>
                </nav>
                <Main />
                <NextScript />
            </body>
        </Html>
    );
};